default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password: password
  host: localhost

sqlite: &sqlite
  adapter: sqlite3 
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  primary:
    <<: *default
    database: concertify_development 
  cable:
    <<: *sqlite
    database: storage/concertify_development_cable.sqlite3
  queue:
    <<: *default
    database: concertify_development_queue
    migrations_paths: db/queue_migrate

test:
  primary:
    <<: *default
    database: concertify_production
  cable:
    <<: *sqlite
    database: storage/concertify_production_cable.sqlite3
  queue:
    <<: *default
    database: concertify_test_queue

production:
  primary:
    <<: *default
    url: <%= ENV["DATABASE_URL"] %>
  queue:
    <<: *default
    url: <%= ENV["DATABASE_URL"] %>
  cable:
    <<: *default
    url: <%= ENV["DATABASE_URL"] %>